#%RAML 1.0
title: Example of request bodies
mediaType: application/json
/users/{userId}:
  get:
    responses:
      200:
        body:
          application/json:
            example: {"id": "JohnS"}