#%RAML 1.0 DataType
type: object
displayName: CloudHub API Analytics
properties:
  clientIp: string
  apiId: string
  apiName: string
  apiVersionId: string
  apiVersionName: string
  application: string
  applicationName: string
  messageId: string
  timestamp: datetime
  requestSize: null
  responseSize: integer
  requestOutcome: string
  verb: string
  resourcePath: string
  statusCode: integer
  userAgentName: string
  userAgentVersion: string
  browser: string
  osFamily: string
  osVersion: string
  osMajorVersion: string
  osMinorVersion: string
  hardwarePlatform: string
  timezone: string
  city: string
  country: string
  continent: string
  postalCode: string
  violatedPolicyName: string
  responseTime: integer