#%RAML 1.0 DataType
type: object
displayName: CloudHub Application Datatype
properties:
  versionId: string
  name: string
  status: string
  vCores: number
  runtime: string
  staticIP: boolean
  lastUpdated: number
  staticIPCount: number
  staticIPAdresses: string
