#%RAML 1.0
title: Use_Case_4
# Expected result
# ApikitMainFlowContainer Designer should not allow the ApikitMainFlowContainer publish

/orders: 
  /{id}: 
    uriParameters: 
      id: 
        type: integer
        examplee: "451"
