#%RAML 1.0 Library
usage: common library for traits

traits: 
  pageable: !include /exchange_modules/a7e2ef79-41aa-4a36-9ca1-1f388917eb12.ahnl/pageable/1.0.1/pageable.raml
  client-id-required: !include /exchange_modules/a7e2ef79-41aa-4a36-9ca1-1f388917eb12.ahnl/client-id-required/1.0.1/client-id-required.raml

  # Other traits, tbd:
  # oauth2: 
  # sortable: 
  # cacheable-time-based: 
  # projectable: 