#%RAML 1.0 DataType
type: object
displayName: Server Datatype
properties:
  id: number
  name: string
  serverType: string
  muleVersion: string
  gatewayVersion: string
  agentVersion: string
  status: string
  clusterId: number
  clusterName: string
  