#%RAML 1.0 Trait
  usage: Apply this trait to enforce client_id identification.
  headers: 
      client_id:
        type: string
        example: "BBBB"
      client_secret:
        type: string
        example: "AAAA"
