#%RAML 1.0
title: ApikitMainFlowContainer

types:
  SomeType:
    properties:
      someProperty: SomeType?
    example:
        someProperty:
          someProperty:
            someProperty: null


/test:
  get:
    responses:
      200:
        body:
          application/json: string

/some-resource:
  get:
    responses:
      200:
        body:
          application/json: SomeTypo
